site_name: Onion - Framework
pages:
  - Intro: index.md
  - Dependency:
    - Introduction: dependency/index.md
    - Invokables: dependency/invokables.md
    - Factories: dependency/factories.md
    - Caching: dependency/caching.md
  - Tutorial: setup.md
  - "Advanced":
    - "Routing": routing.md
    - "Modules": modules.md
theme: readthedocs
