site_name: Onion - Framework
pages:
  - Intro: index.md
  - Tutorial: setup.md
  - Dependency:
    - Introduction: dependency/index.md
    - Invokables: dependency/invokables.md
    - Factories: dependency/factories.md
    - Caching: dependency/caching.md
    - Delegation: dependency/delegation.md
  - Routing:
    - Introduction: routing/index.md
  - Hydration: hydratable.md
  - Collections: collections.md
  - Rest: rest/index.md
  - "Advanced":
    - "Modules": modules.md
theme: readthedocs
